### PR TITLE
fixed bug when using different store_dir then 'CA'

### PR DESCRIPTION
**Pull request by jinxxik**
Hi,

I am using your puppet module, i thing its best way how to use windows certificates in puppet. I found that you are using hardcoded store_dir 'CA' which doesn't reflect used settings.

Have a nice day :-)

### CODE REVIEW

**Comment by ffrank** [comment]
Huge delay here - sorry.

@jinxxik do you have comment to @stack72's questions?

I'd need some context to properly comment on the proposal. Where are those "used settings" you refer to located? Where do they originate? What application(s) are we talking here? (IIS,...)

**Comment by jinxxik** [comment]
Hello,

Maybe its not a valid solution after all. I was installing self signed root ca certificate which will be recognized in the system. Did manual action through the windows wizard, looked to the listed certificates in trusted root ca store? I think and i wanted to do the same with your module.. This fix worked for me, but when i see it now, maybe its not solution after all. Try add self signed root ca cert and e.g. Sign web SSL certificate and try to open a web page with chrome. If it works without my pull request, simply close it.

Have a nice day

**Comment by ffrank** [comment]
So my take-away is: You modified your system to trust a self-signed CA of your own. This patch made it possible for you to install certificates that were signed by this custom CA (or its intermediates?).

If custom CAs are currently not supported, it would be worthwhile to pursue such support IMO. But that would need

 * some conceptual specification
 * clear instructions on how to install such CAs
 * a mode of operation that is compatible with the current state of the module

**Comment by daenney** [comment]
Since we're not exactly clear on if this is the right way forward, the current branch is no longer mergeable and no activity has occurred in 6 months I'm closing this. Feel free to re-open this if we a better way forward has come to mind.

**Pull request closed without merging**
